import React, { useState } from 'react'
import { Layout } from '../components/Layout'
import Head from 'next/head'
import { PokeItem } from '../components/PokeItem'
import { doc, getDoc } from 'firebase/firestore'
import { db } from '../../firebaseClient'
import { useAuth } from '../hooks/useAuth'
import { PokeLoader } from '../components/PokeLoader'
import { PrivateRoute } from '../components/PrivateRoute'

export const Favorites = () => {
  const { currentUser } = useAuth()
  const [favorites, setFavorites] = useState([])

  if (currentUser) {
    const favoriteRef = doc(db, 'favorites', currentUser?.uid)
    getDoc(favoriteRef)
      .then((response: any) => {
        setFavorites(response.data().pokemons)
      })
      .catch((error) => {
        console.log(error)
      })
  }

  return (
    <PrivateRoute>
      <Head>
        <title>FindPoke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {favorites.length === 0 && <PokeLoader />}
        {favorites.map((favorite: any) => (
          <PokeItem key={favorite} name={favorite} />
        ))}
      </Layout>
    </PrivateRoute>
  )
}

export default Favorites
