import React, { useEffect, useState } from 'react'
import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/Layout'
import { PokeItem } from '../components/PokeItem'
import { useQuery } from '../hooks/useQuery'
import { useAuth } from '../hooks/useAuth'

interface PokemonProps {
  name: string
  url: string
}

const Home: NextPage = () => {
  const [pokemons, setPokemons] = useState([])
  const { query } = useQuery()
  const { currentUser } = useAuth()

  useEffect(() => {
    axios.get('https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0')
      .then((response) => {
        setPokemons(response.data.results)
      })
      .catch((error) => {
        console.log(error)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>FindPoke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        { currentUser && `Seja bem-vindo ${currentUser.displayName}` }
        { query && pokemons.filter((pokemon: PokemonProps) => (
          pokemon.name.includes(query.toLowerCase())
        )).map((pokemon: PokemonProps) => (
          <PokeItem key={pokemon.name} name={pokemon.name} />
        )) }
      </Layout>
    </div>
  )
}

export default Home
